:bug: PartialMetadataObject should preserve GVK information
kubernetes-sigs/controller-runtime pull request #1484
Opened 2021-04-19 16:48 UTC by vincepri

Currently we have a bug that GVK information is not passed into mapping
functions when using the OnlyMetadata option in the builder. This patch
adds a wrapper that preserves the GVK information when events come in.

Signed-off-by: Vince Prignano <vincepri@vmware.com>

/hold

for further review

2021-04-19 17:51 UTC, vincepri commented
/retest

2021-04-19 18:33 UTC, vincepri commented
/retest

2021-04-19 20:55 UTC, DirectXMan12 requested changes
It occurs to me -- we manually construct a `WithoutConversionCodecFactory`, and as per https://github.com/kubernetes/kubernetes/issues/80609, that's the thing, eventually, that's actually stripping the GVK.  Could we just construct our own NegotiatedSerializer instead that doesn't do this and just uses the decoder directly?

Something like

```go
cfg.NegotiatedSerializer = WithoutConversionGVKCodecFactory{CodecFactory: codecs}

// then just implement the required methods similarly to the existing codec factory, except without using WithoutVersionDecoder
```

2021-04-27 15:25 UTC, vincepri commented
@DirectXMan12 @alvaroaleman A little update on this issue, while the NegotiatedSerializer would have been a good solution to explore, it's way too complicated and there are limitations coming from client-go and how the serializers are being used; moreover, the api-server when querying for a metadata object returns TypeMeta filled as:

```
TypeMeta: {
  Kind: "PartialObjectMetadata",
  APIVersion: "meta.k8s.io/v1",
}
```

Which seems to be the expected behavior described in the associated KEP.

For this reason, I updated this PR to follow a different approach: in the client and cache code we now make sure to always preserve the type information coming from the client. We were already doing something similar for Patch/Update on all calls in `client.go` file, I extended that behavior for Get/List calls when a PartialObjectMetadata[List] object is detected. In addition, the cache now makes sure to preserve the GVK when a new handler is passed in which should cover most if not all uses for the metadata objects.

The only one discrepancy I can think about between the metadata client and the unstructured one is for `List` calls: the unstructured client when querying a `apps/v1 DeploymentList` for example it returns each item in the list with TypeMeta information filled in (`apps/v1 Deployment` for the example). Should we do the same for Metadata List calls? If so, how can we reliably get the TypeMeta information of an object in a List GVK?

Note: The unstructured client already behaves properly and its default (forced) serializer makes sure to not clear the TypeMeta information.

2021-04-27 15:50 UTC, vincepri commented
/hold cancel

2021-04-27 18:20 UTC, vincepri commented on pkg/client/apiutil/apimachinery.go
> +// SerializerWithDecodedGVK is a CodecFactory that overrides the DecoderToVersion of a WithoutConversionCodecFactory
Done!

2021-04-27 18:26 UTC, alvaroaleman approved these changes
/lgtm
/approve

2021-04-27 18:26 UTC, vincepri commented
/milestone v0.9.x

2021-04-27 18:27 UTC, merged